name: Build and Deploy to IIS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet publish -c Release -o published_app

      - name: Deploy to IIS via WinRM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IIS_SERVER_IP }}
          username: ${{ secrets.IIS_USERNAME }}
          password: ${{ secrets.IIS_PASSWORD }}
          script: |
            Stop-Service W3SVC -Force
            Remove-Item -Recurse -Force "C:\inetpub\wwwroot\${{ secrets.IIS_SITE_NAME }}"
            Copy-Item -Recurse -Force published_app "C:\inetpub\wwwroot\${{ secrets.IIS_SITE_NAME }}"
            Start-Service W3SVC
