name: Deploy to IIS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      - name: Stop IIS Website
        run: |
          Import-Module WebAdministration
          Stop-WebSite -Name "Default Web Site"
        shell: powershell

      - name: Deploy Application
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\cv-roaster\*"
          Copy-Item -Recurse -Force ./publish/* "C:\inetpub\wwwroot\cv-roaster\"
        shell: powershell

      - name: Start IIS Website
        run: |
          Start-WebSite -Name "Default Web Site"
        shell: powershell
